# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 480)
        self.submitButton = QtWidgets.QPushButton(parent=Dialog)
        self.submitButton.setGeometry(QtCore.QRect(80, 360, 261, 81))
        self.submitButton.setObjectName("submitButton")
        self.stopButton = QtWidgets.QPushButton(parent=Dialog)
        self.stopButton.setGeometry(QtCore.QRect(370, 360, 261, 81))
        self.stopButton.setObjectName("stopButton")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=Dialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(0, 0, 194, 23))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.predefinedConditionsButton = QtWidgets.QToolButton(parent=Dialog)
        self.predefinedConditionsButton.setGeometry(QtCore.QRect(560, 10, 131, 51))
        self.predefinedConditionsButton.setObjectName("predefinedConditionsButton")
        self.increaseButton = QtWidgets.QPushButton(parent=Dialog)
        self.increaseButton.setGeometry(QtCore.QRect(270, 100, 81, 71))
        self.increaseButton.setObjectName("increaseButton")
        self.decreaseButton = QtWidgets.QPushButton(parent=Dialog)
        self.decreaseButton.setGeometry(QtCore.QRect(360, 100, 81, 71))
        self.decreaseButton.setObjectName("decreaseButton")
        self.stateFrame = QtWidgets.QFrame(parent=Dialog)
        self.stateFrame.setGeometry(QtCore.QRect(450, 10, 71, 61))
        self.stateFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stateFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stateFrame.setObjectName("stateFrame")
        self.stateLabel = QtWidgets.QLabel(parent=Dialog)
        self.stateLabel.setGeometry(QtCore.QRect(410, 30, 49, 16))
        self.stateLabel.setObjectName("stateLabel")
        self.frequencyLabel = QtWidgets.QLabel(parent=Dialog)
        self.frequencyLabel.setGeometry(QtCore.QRect(60, 120, 121, 41))
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.StrokeLabel = QtWidgets.QLabel(parent=Dialog)
        self.StrokeLabel.setGeometry(QtCore.QRect(60, 220, 121, 41))
        self.StrokeLabel.setObjectName("StrokeLabel")
        self.increaseButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.increaseButton_2.setGeometry(QtCore.QRect(270, 200, 81, 71))
        self.increaseButton_2.setObjectName("increaseButton_2")
        self.decreaseButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.decreaseButton_2.setGeometry(QtCore.QRect(360, 200, 81, 71))
        self.decreaseButton_2.setObjectName("decreaseButton_2")
        self.measurementsPlotsButton = QtWidgets.QToolButton(parent=Dialog)
        self.measurementsPlotsButton.setGeometry(QtCore.QRect(560, 80, 131, 51))
        self.measurementsPlotsButton.setObjectName("measurementsPlotsButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.submitButton.setText(_translate("Dialog", "Submit configuration"))
        self.stopButton.setText(_translate("Dialog", "STOP"))
        self.predefinedConditionsButton.setText(_translate("Dialog", "Predefined Conditions"))
        self.increaseButton.setText(_translate("Dialog", "+ 10"))
        self.decreaseButton.setText(_translate("Dialog", "- 10"))
        self.stateLabel.setText(_translate("Dialog", "State"))
        self.frequencyLabel.setText(_translate("Dialog", "Frequency =   Bpm "))
        self.StrokeLabel.setText(_translate("Dialog", "Stroke Length =  cm"))
        self.increaseButton_2.setText(_translate("Dialog", "+ 10"))
        self.decreaseButton_2.setText(_translate("Dialog", "- 10"))
        self.measurementsPlotsButton.setText(_translate("Dialog", "Measurements Plots"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
