# Form implementation generated from reading ui file 'second_sketch.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stateIndcator = QtWidgets.QLabel(parent=self.centralwidget)
        self.stateIndcator.setGeometry(QtCore.QRect(910, 20, 91, 41))
        self.stateIndcator.setStyleSheet("background-color: gray;\n"
"border-radius: 20px;\n"
"border: 2px solid black;\n"
"")
        self.stateIndcator.setText("")
        self.stateIndcator.setObjectName("stateIndcator")
        self.recordButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(900, 400, 111, 71))
        self.recordButton.setObjectName("recordButton")
        self.predefButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.predefButton.setGeometry(QtCore.QRect(900, 80, 111, 71))
        self.predefButton.setObjectName("predefButton")
        self.settingsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(900, 480, 111, 71))
        self.settingsButton.setObjectName("settingsButton")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(900, 160, 111, 71))
        self.saveButton.setObjectName("saveButton")
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(900, 320, 111, 71))
        self.stopButton.setObjectName("stopButton")
        self.resetButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(900, 240, 111, 71))
        self.resetButton.setObjectName("resetButton")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 80, 122, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lvpLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.lvpLabel.setFont(font)
        self.lvpLabel.setObjectName("lvpLabel")
        self.verticalLayout.addWidget(self.lvpLabel)
        self.aopLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.aopLabel.setFont(font)
        self.aopLabel.setObjectName("aopLabel")
        self.verticalLayout.addWidget(self.aopLabel)
        self.lapLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.lapLabel.setFont(font)
        self.lapLabel.setObjectName("lapLabel")
        self.verticalLayout.addWidget(self.lapLabel)
        self.flowLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.flowLabel.setFont(font)
        self.flowLabel.setObjectName("flowLabel")
        self.verticalLayout.addWidget(self.flowLabel)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 10, 691, 101))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hrStackedWidget = QtWidgets.QStackedWidget(parent=self.widget)
        self.hrStackedWidget.setObjectName("hrStackedWidget")
        self.hrPage2 = QtWidgets.QWidget()
        self.hrPage2.setObjectName("hrPage2")
        self.btnHRincrease = QtWidgets.QPushButton(parent=self.hrPage2)
        self.btnHRincrease.setGeometry(QtCore.QRect(140, 0, 51, 41))
        self.btnHRincrease.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.btnHRincrease.setObjectName("btnHRincrease")
        self.btnHRdecrease = QtWidgets.QPushButton(parent=self.hrPage2)
        self.btnHRdecrease.setGeometry(QtCore.QRect(140, 50, 51, 41))
        self.btnHRdecrease.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.btnHRdecrease.setObjectName("btnHRdecrease")
        self.hrLabel = QtWidgets.QLabel(parent=self.hrPage2)
        self.hrLabel.setGeometry(QtCore.QRect(8, 5, 131, 91))
        self.hrLabel.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.hrLabel.setObjectName("hrLabel")
        self.hrStackedWidget.addWidget(self.hrPage2)
        self.hrPage1_2 = QtWidgets.QWidget()
        self.hrPage1_2.setObjectName("hrPage1_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.hrPage1_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.hrStackedWidget.addWidget(self.hrPage1_2)
        self.horizontalLayout.addWidget(self.hrStackedWidget)
        self.svStackedWidget = QtWidgets.QStackedWidget(parent=self.widget)
        self.svStackedWidget.setObjectName("svStackedWidget")
        self.svPage1 = QtWidgets.QWidget()
        self.svPage1.setObjectName("svPage1")
        self.btnSVincrease = QtWidgets.QPushButton(parent=self.svPage1)
        self.btnSVincrease.setGeometry(QtCore.QRect(140, 0, 51, 41))
        self.btnSVincrease.setObjectName("btnSVincrease")
        self.btnSVincrease.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.btnSVdecrease = QtWidgets.QPushButton(parent=self.svPage1)
        self.btnSVdecrease.setGeometry(QtCore.QRect(140, 50, 51, 41))
        self.btnSVdecrease.setObjectName("btnSVdecrease")
        self.btnSVdecrease.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.svLabel = QtWidgets.QLabel(parent=self.svPage1)
        self.svLabel.setGeometry(QtCore.QRect(8, 5, 131, 91))
        self.svLabel.setObjectName("svLabel")
        self.svStackedWidget.addWidget(self.svPage1)
        self.svPage2 = QtWidgets.QWidget()
        self.svPage2.setObjectName("svPage2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.svPage2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.svStackedWidget.addWidget(self.svPage2)
        self.horizontalLayout.addWidget(self.svStackedWidget)
        self.resStackedWidget = QtWidgets.QStackedWidget(parent=self.widget)
        self.resStackedWidget.setObjectName("resStackedWidget")
        self.resPage1 = QtWidgets.QWidget()
        self.resPage1.setObjectName("resPage1")
        self.btnResistance = QtWidgets.QPushButton(parent=self.resPage1)
        self.btnResistance.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.btnResistance.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.btnResistance.setObjectName("btnResistance")
        self.resStackedWidget.addWidget(self.resPage1)
        self.resPage2 = QtWidgets.QWidget()
        self.resPage2.setObjectName("resPage2")
        self.btnResIncrease = QtWidgets.QPushButton(parent=self.resPage2)
        self.btnResIncrease.setGeometry(QtCore.QRect(140, 0, 51, 41))
        self.btnResIncrease.setObjectName("btnResIncrease")
        self.btnResIncrease.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.btnResDecrease = QtWidgets.QPushButton(parent=self.resPage2)
        self.btnResDecrease.setGeometry(QtCore.QRect(140, 50, 51, 41))
        self.btnResDecrease.setObjectName("btnResDecrease")
        self.btnResDecrease.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30px;\n"
"    color: white;\n"
"}\n"
"")
        self.resLabel = QtWidgets.QLabel(parent=self.resPage2)
        self.resLabel.setGeometry(QtCore.QRect(10, 5, 131, 91))
        self.resLabel.setObjectName("resLabel")
        self.resStackedWidget.addWidget(self.resPage2)
        self.horizontalLayout.addWidget(self.resStackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.hrStackedWidget.setCurrentIndex(1)
        self.svStackedWidget.setCurrentIndex(1)
        self.resStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordButton.setText(_translate("MainWindow", "RECORD"))
        self.predefButton.setText(_translate("MainWindow", "Predefined\nScenarios"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
        self.saveButton.setText(_translate("MainWindow", "SAVE\nConfiguration"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
        self.lvpLabel.setText(_translate("MainWindow", "LVP"))
        self.aopLabel.setText(_translate("MainWindow", "AOP"))
        self.lapLabel.setText(_translate("MainWindow", "LAP"))
        self.flowLabel.setText(_translate("MainWindow", "FLOW"))
        self.btnHRincrease.setText(_translate("MainWindow", "+"))
        self.btnHRdecrease.setText(_translate("MainWindow", "-"))
        self.hrLabel.setText(_translate("MainWindow", "Heart Rate"))
        self.pushButton.setText(_translate("MainWindow", "Heart Rate"))
        self.btnSVincrease.setText(_translate("MainWindow", "+"))
        self.btnSVdecrease.setText(_translate("MainWindow", "-"))
        self.svLabel.setText(_translate("MainWindow", "Stroke Volume"))
        self.pushButton_2.setText(_translate("MainWindow", "Stroke Volume"))
        self.btnResistance.setText(_translate("MainWindow", "Resistance"))
        self.btnResIncrease.setText(_translate("MainWindow", "+"))
        self.btnResDecrease.setText(_translate("MainWindow", "-"))
        self.resLabel.setText(_translate("MainWindow", "Resistance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
