# Form implementation generated from reading ui file 'second_sketch.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# run the following command to convert the .ui file to .py file
#  python -m PyQt6.uic.pyuic -x file_name.ui -o file_name.py  

from PyQt5 import QtCore, QtGui, QtWidgets  # <-- switched to PyQt5!

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        """self.stateIndcator = QtWidgets.QLabel(self.centralwidget)
        self.stateIndcator.setGeometry(QtCore.QRect(910, 20, 91, 41))
        self.stateIndcator.setStyleSheet("background-color: gray;\nborder-radius: 20px;\nborder: 2px solid black;\n")
        self.stateIndcator.setText("")
        self.stateIndcator.setObjectName("stateIndcator")"""
        self.stateIndicator = QtWidgets.QTextEdit(self.centralwidget)
        self.stateIndicator.setGeometry(QtCore.QRect(910, 20, 91, 41))
        self.stateIndicator.setReadOnly(True)
        self.stateIndicator.setStyleSheet("""
            background-color: black;
            color: white;
            border-radius: 20px;
            border: 2px solid black;
            font-size: 12px;
        """)
        self.stateIndicator.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stateIndicator.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stateIndicator.setText("")
        self.stateIndicator.setObjectName("stateIndicator")

        # Bottom Buttons Row
        self.bottomButtonsWidget = QtWidgets.QWidget(self.centralwidget)
        self.bottomButtonsWidget.setGeometry(QtCore.QRect(0, 560, 1024, 80))
        self.bottomButtonsWidget.setObjectName("bottomButtonsWidget")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottomButtonsWidget)
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.predefButton = QtWidgets.QPushButton(self.bottomButtonsWidget)
        self.predefButton.setObjectName("predefButton")
        self.horizontalLayout_2.addWidget(self.predefButton)

        self.calibrateButton = QtWidgets.QPushButton(self.bottomButtonsWidget)
        self.calibrateButton.setObjectName("calibrateButton")
        self.horizontalLayout_2.addWidget(self.calibrateButton)

        self.resetButton = QtWidgets.QPushButton(self.bottomButtonsWidget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)

        self.stopButton = QtWidgets.QPushButton(self.bottomButtonsWidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)

        self.recordButton = QtWidgets.QPushButton(self.bottomButtonsWidget)
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout_2.addWidget(self.recordButton)

        self.settingsButton = QtWidgets.QPushButton(self.bottomButtonsWidget)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_2.addWidget(self.settingsButton)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        #self.layoutWidget.setGeometry(QtCore.QRect(760, 80, 122, 481))
        self.layoutWidget.setGeometry(QtCore.QRect(760, 140, 122, 421))
        self.layoutWidget.setObjectName("layoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.lvpLabel = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.lvpLabel.setFont(font)
        self.lvpLabel.setCheckable(True)
        self.lvpLabel.setChecked(True)
        self.lvpLabel.setObjectName("lvpLabel")
        self.verticalLayout.addWidget(self.lvpLabel)

        self.aopLabel = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.aopLabel.setFont(font)
        self.aopLabel.setCheckable(True)
        self.aopLabel.setChecked(True)
        self.aopLabel.setObjectName("aopLabel")
        self.verticalLayout.addWidget(self.aopLabel)

        self.lapLabel = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.lapLabel.setFont(font)
        self.lapLabel.setCheckable(True)
        self.lapLabel.setChecked(True)
        self.lapLabel.setObjectName("lapLabel")
        self.verticalLayout.addWidget(self.lapLabel)

        self.flowLabel = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(24)
        self.flowLabel.setFont(font)
        self.flowLabel.setCheckable(True)
        self.flowLabel.setChecked(True)
        self.flowLabel.setObjectName("flowLabel")
        self.verticalLayout.addWidget(self.flowLabel)


        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 10, 691, 101))
        self.widget.setObjectName("widget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.hrStackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.hrStackedWidget.setObjectName("hrStackedWidget")

        self.hrPage2 = QtWidgets.QWidget()
        self.hrPage2.setObjectName("hrPage2")

        self.btnHRincrease = QtWidgets.QPushButton(self.hrPage2)
        self.btnHRincrease.setGeometry(QtCore.QRect(140, 0, 51, 41))
        self.btnHRincrease.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")
        self.btnHRincrease.setObjectName("btnHRincrease")

        self.btnHRdecrease = QtWidgets.QPushButton(self.hrPage2)
        self.btnHRdecrease.setGeometry(QtCore.QRect(140, 50, 51, 41))
        self.btnHRdecrease.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")
        self.btnHRdecrease.setObjectName("btnHRdecrease")

        self.hrLabel = QtWidgets.QLabel(self.hrPage2)
        self.hrLabel.setGeometry(QtCore.QRect(8, 5, 131, 91))
        self.hrLabel.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")
        self.hrLabel.setObjectName("hrLabel")
        self.hrStackedWidget.addWidget(self.hrPage2)

        self.hrPage1_2 = QtWidgets.QWidget()
        self.hrPage1_2.setObjectName("hrPage1_2")
        self.pushButton = QtWidgets.QPushButton(self.hrPage1_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.pushButton.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")
        self.pushButton.setObjectName("pushButton")
        self.hrStackedWidget.addWidget(self.hrPage1_2)

        self.horizontalLayout.addWidget(self.hrStackedWidget)

        self.svStackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.svStackedWidget.setObjectName("svStackedWidget")

        self.svPage1 = QtWidgets.QWidget()
        self.svPage1.setObjectName("svPage1")

        self.btnSVincrease = QtWidgets.QPushButton(self.svPage1)
        self.btnSVincrease.setGeometry(QtCore.QRect(140, 0, 51, 41))
        self.btnSVincrease.setObjectName("btnSVincrease")
        self.btnSVincrease.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")

        self.btnSVdecrease = QtWidgets.QPushButton(self.svPage1)
        self.btnSVdecrease.setGeometry(QtCore.QRect(140, 50, 51, 41))
        self.btnSVdecrease.setObjectName("btnSVdecrease")
        self.btnSVdecrease.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")

        self.svLabel = QtWidgets.QLabel(self.svPage1)
        self.svLabel.setGeometry(QtCore.QRect(8, 5, 131, 91))
        self.svLabel.setObjectName("svLabel")
        self.svStackedWidget.addWidget(self.svPage1)

        self.svPage2 = QtWidgets.QWidget()
        self.svPage2.setObjectName("svPage2")
        self.pushButton_2 = QtWidgets.QPushButton(self.svPage2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.pushButton_2.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.svStackedWidget.addWidget(self.svPage2)

        self.horizontalLayout.addWidget(self.svStackedWidget)

        self.resStackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.resStackedWidget.setObjectName("resStackedWidget")

        self.resPage1 = QtWidgets.QWidget()
        self.resPage1.setObjectName("resPage1")
        self.btnResistance = QtWidgets.QPushButton(self.resPage1)
        self.btnResistance.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.btnResistance.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")
        self.btnResistance.setObjectName("btnResistance")
        self.resStackedWidget.addWidget(self.resPage1)

        self.resPage2 = QtWidgets.QWidget()
        self.resPage2.setObjectName("resPage2")
        self.btnResIncrease = QtWidgets.QPushButton(self.resPage2)
        self.btnResIncrease.setGeometry(QtCore.QRect(140, 0, 51, 41))
        self.btnResIncrease.setObjectName("btnResIncrease")
        self.btnResIncrease.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")

        self.btnResDecrease = QtWidgets.QPushButton(self.resPage2)
        self.btnResDecrease.setGeometry(QtCore.QRect(140, 50, 51, 41))
        self.btnResDecrease.setObjectName("btnResDecrease")
        self.btnResDecrease.setStyleSheet("QPushButton { border: none; background-color: transparent; font-size: 30px; color: white; }")

        self.resLabel = QtWidgets.QLabel(self.resPage2)
        self.resLabel.setGeometry(QtCore.QRect(10, 5, 131, 91))
        self.resLabel.setObjectName("resLabel")
        self.resStackedWidget.addWidget(self.resPage2)

        self.horizontalLayout.addWidget(self.resStackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.hrStackedWidget.setCurrentIndex(1)
        self.svStackedWidget.setCurrentIndex(1)
        self.resStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordButton.setText(_translate("MainWindow", "RECORD"))
        self.predefButton.setText(_translate("MainWindow", "Predefined\nScenarios"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
        self.calibrateButton.setText(_translate("MainWindow", "Zero\nPressures"))
        self.stopButton.setText(_translate("MainWindow", "STOP\nMOTOR"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
        self.lvpLabel.setText(_translate("MainWindow", "LVP"))
        self.aopLabel.setText(_translate("MainWindow", "AOP"))
        self.lapLabel.setText(_translate("MainWindow", "LAP"))
        self.flowLabel.setText(_translate("MainWindow", "FLOW"))
        self.btnHRincrease.setText(_translate("MainWindow", "+"))
        self.btnHRdecrease.setText(_translate("MainWindow", "-"))
        self.hrLabel.setText(_translate("MainWindow", "Heart Rate"))
        self.pushButton.setText(_translate("MainWindow", "Heart Rate"))
        self.btnSVincrease.setText(_translate("MainWindow", "+"))
        self.btnSVdecrease.setText(_translate("MainWindow", "-"))
        self.svLabel.setText(_translate("MainWindow", "Stroke Volume"))
        self.pushButton_2.setText(_translate("MainWindow", "Stroke Volume"))
        self.btnResistance.setText(_translate("MainWindow", "Resistance"))
        self.btnResIncrease.setText(_translate("MainWindow", "+"))
        self.btnResDecrease.setText(_translate("MainWindow", "-"))
        self.resLabel.setText(_translate("MainWindow", "Resistance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
